<?php
include_once 'dbh.inc.php';

$PostalCode = isset($_POST['PostalCode']) ? $_POST['PostalCode'] : '';
$AccessToken = isset($_POST['AccessToken']) ? $_POST['AccessToken'] : '';
$accesstoken = '';
$service_type ='Street ID';


$soapUrl = "https://apigw22.cyta.com.cy:8243/GetAddressList/1.0.0";
$soapUser = "X5873QBUeJf135WJNCyl_2DTIeka";  //  username
$soapPassword = "Fy8NLbX0GTQx2WsI0_sl6m2d_N4a"; // password


$username='X5873QBUeJf135WJNCyl_2DTIeka';
$password='Fy8NLbX0GTQx2WsI0_sl6m2d_N4a';
$url='https://apigw22.cyta.com.cy:8243/token';



// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://apigw22.cyta.com.cy:8243/token');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_USERPWD, 'X5873QBUeJf135WJNCyl_2DTIeka' . ':' . 'Fy8NLbX0GTQx2WsI0_sl6m2d_N4a');

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

$json   = json_decode($result);
$atoken = $json->access_token;

curl_close ($ch);





$xml_post_string = '<?xml version="1.0" encoding="utf-8"?>
                    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:get="http://fmw.cyta.com.cy/GetAddressListByPostalCode/"> 
                        <soapenv:Header/>   
                        <soapenv:Body>
                          <get:GetAddressListByPostalCode>                        
                            <in> 
                                <GetAddressListByPostalCodePayload>
                                <PostalCode>'.$PostalCode.'</PostalCode>
                                </GetAddressListByPostalCodePayload>
                            </in>
                          </get:GetAddressListByPostalCode>
                        </soapenv:Body>
                     </soapenv:Envelope>';

echo '<prexmlstring>'; print_r($xml_post_string); echo '</prexmlstring>';


$headers = array(
    "POST /GetAddressList/1.0.0 HTTP/1.1",
    "Accept-Encoding: gzip,deflate",
    "Content-Type: text/xml;charset=UTF-8",
    "SOAPAction: \"http://fmw.cyta.com.cy/GetAddressListByPostalCode/GetAddressListByPostalCode\"",
    "Authorization: Bearer $atoken",
    "Host: apigw22.cyta.com.cy:8243",
    "Content-length: ".strlen($xml_post_string),
);

$url = $soapUrl;

$ch = curl_init();
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERPWD, $soapUser.":".$soapPassword); // username and password - declared at the top of the doc
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
curl_setopt($ch, CURLOPT_TIMEOUT, 10);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $xml_post_string); // the SOAP request
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

// converting
$response = curl_exec($ch);
$err = curl_error($ch);
$info = curl_getinfo($ch);
curl_close($ch);

// converting
$response1 = str_replace("<soap:Body>","",$response);
$response2 = str_replace("</soap:Body>","",$response1);





$ns = "http://fmw.cyta.com.cy/GetAddressListByPostalCode/";
$document = new DOMDocument();
$document->loadXml($response);

$re11 = $document->getElementsByTagName('ResponseCode');
$re22 = $document->getElementsByTagName('ErrorDescription');
$re33 = $document->getElementsByTagName('StreetCount');
$re44 = $document->getElementsByTagName('StreetCollection');
$re55 = $document->getElementsByTagName('StreetID');
$re66 = $document->getElementsByTagName('StreetNameEnglish');
$re77 = $document->getElementsByTagName('StreetType');
$ResponseCode = '';
$ErrorDescription = '';
$StreetCount = '';
$StreetCollection='';
$StreetID='';
$StreetNameEnglish='';
$StreetType='';

foreach ($re11 as $book) {
    $ResponseCode = $book->nodeValue;

}
foreach ($re22 as $book) {
    $ErrorDescription = $book->nodeValue;

}foreach ($re33 as $book) {
    $StreetCount = $book->nodeValue;

}foreach ($re44 as $book) {
    $StreetCollection = $book->nodeValue;

}
foreach ($re55 as $book) {
    $StreetID = $book->nodeValue;

}
foreach ($re66 as $book) {
    $StreetNameEnglish = $book->nodeValue;

}
foreach ($re77 as $book) {
    $StreetType = $book->nodeValue;

}

    switch ($ResponseCode) {
        case "-1":
            echo "System Error";
            break;
        case "0":
            echo "Success";
            break;
        case "1":
            echo "Postal Code not found";
            break;

        default:
            echo "Invalid/Expired Access token";
    }

if (strlen($response) > 1) {

 echo
    '

                    <header>
                    <nav>
                   <div>
                <table style="float: left;" border="1" >
                    <tr>
                        <td align="right">ResponseCode</td>
                        <td align="left">', $ResponseCode, '</td>
                    </tr>
                    <tr>
                        <td align="right">Error Description</td>
                        <td align="left">', $ErrorDescription, '</td>
                    </tr>
                    <tr>
                        <td align="right">Street Count</td>
                        <td align="left">', $StreetCount, '</td>
                    </tr>
                    
                 
                   


                </table>
                </nav>
                </header>
                
          ';


?>
<table style="float: right;" border="1">

  <tbody>

<?php foreach ($re44 as $book) {
    $StreetCollection = $book->nodeValue;

?>
    <tr>
        <td align="right">Street ID</td>
      <td align="left"><?php echo  $StreetCollection; echo "<br>" ?></td>

    </tr>

<?php } ?>
  </tbody>
</table>
    <?php
}



if ($ResponseCode == '0') {

}
//echo "Data sent";
//exit();

